Repository SU-SWS/decanter, pull requests merged in 2019-03, with the labels that each got.

#264 72 main nav
  .codeclimate.yml
  .eslintrc
  Gruntfile.js
  core/css/decanter.css
  core/img/caret-down-black.png
  core/img/caret-down-black.svg
  core/img/caret-down-white.svg
  core/img/close-black.svg
  core/img/hamburger-black.svg
  core/img/minus-black.svg
  core/img/minus-white.png
  core/img/minus-white.svg
  core/img/plus-black.svg
  core/img/plus-white.png
  core/img/plus-white.svg
  core/js/decanter.js
  core/js/decanter.min.js
  core/scss/components/index.scss
  core/scss/components/main-nav/_main-nav--center.scss
  core/scss/components/main-nav/_main-nav--light.scss
  core/scss/components/main-nav/_main-nav--mobile-search.scss
  core/scss/components/main-nav/_main-nav--right.scss
  core/scss/components/main-nav/_main-nav.scss
  core/scss/components/main-nav/index.scss
  core/scss/components/site-search/_site-search.scss
  core/scss/utilities/mixins/animation/_fancy-hover.scss
  core/scss/utilities/mixins/animation/index.scss
  core/scss/utilities/mixins/index.scss
  core/templates/components/brand-bar/brand-bar.twig
  core/templates/components/cta/cta.twig
  core/templates/components/logo/logo.twig
  core/templates/components/main-nav/main-nav.json
  core/templates/components/main-nav/main-nav.twig
  core/templates/components/site-search/site-search.twig
  kss/builder/decanter/kss-assets/css/kss.css
  kss/builder/decanter/scss/_brand-bar.scss
  kss/builder/decanter/scss/_content.scss
  kss/builder/decanter/scss/_fullscreen.scss
  kss/builder/decanter/scss/_main-nav.scss
  kss/kss-config.json
  package-lock.json
Labels: enhancement

#307 120 skiplinks b
  core/scss/components/skiplinks/_skiplinks.scss
  core/templates/components/skiplinks/link.twig
  core/templates/components/skiplinks/skiplinks.twig
  core/templates/components/skiplinks/target.twig
Labels: enhancement

#303 120 Skiplinks
  core/css/decanter.css
  core/scss/components/index.scss
  core/scss/components/site-search/_site-search.scss
  core/scss/components/skiplinks/_skiplinks.scss
  core/scss/components/skiplinks/index.scss
  core/scss/components/skipnav/_skipnav.scss
  core/scss/core/helpers/_sr-only-element.scss
  core/scss/core/helpers/_sr-only-text.scss
  core/scss/core/helpers/_sr-only.scss
  core/scss/core/helpers/index.scss
  core/scss/elements/input/_input.scss
  core/scss/utilities/mixins/accessibility/_skiplinks.scss
  core/scss/utilities/mixins/accessibility/_skipnav.scss
  core/scss/utilities/mixins/accessibility/_sr-only.scss
  core/scss/utilities/mixins/accessibility/index.scss
  core/templates/components/skiplinks/link.twig
  core/templates/components/skiplinks/skiplinks.json
  core/templates/components/skiplinks/skiplinks.twig
  core/templates/components/skiplinks/target.twig
  core/templates/components/skipnav/skipnav.json
  core/templates/components/skipnav/skipnav.twig
  core/templates/elements/input/input.twig
  kss/builder/decanter/kss-assets/css/kss.css
  kss/builder/decanter/scss/_skiplinks.scss
  kss/builder/decanter/scss/kss.scss
Labels: Accessibility, enhancement

#309 Tweaking modular-spacing mixin to be more user friendly
  core/css/decanter.css
  core/scss/components/card/_card--horizontal.scss
  core/scss/components/card/_card.scss
  core/scss/components/global-footer/_global-footer.scss
  core/scss/utilities/mixins/modular-scale/_modular-spacing.scss
Labels: enhancement

#304 Add linear gradient background mixin
  core/scss/components/main-nav/_main-nav.scss
  core/scss/utilities/functions/string/_convert-angle.scss
  core/scss/utilities/functions/string/index.scss
  core/scss/utilities/functions/type-checks/_is-direction-or-angle.scss
  core/scss/utilities/functions/type-checks/index.scss
  core/scss/utilities/mixins/gradient/_linear-gradient.scss
  core/scss/utilities/mixins/gradient/index.scss
  core/scss/utilities/mixins/index.scss
  core/scss/utilities/mixins/modular-scale/_modular-spacing.scss
  kss/builder/decanter/kss-assets/css/kss.css
  kss/builder/decanter/scss/_brand-bar.scss
Labels: enhancement

#330 Update _alert--info.scss
  core/css/decanter.css
  core/scss/components/alert/_alert--error.scss
  core/scss/components/alert/_alert--info.scss
  core/scss/components/alert/_alert--success.scss
  core/scss/components/alert/_alert--warning.scss
  core/scss/components/alert/_alert.scss
  core/templates/components/alert/alert.json
Labels: Accessibility, bug

#289 5 Lines Lockup + Variants
  core/css/decanter.css
  core/scss/components/lockup/_lockup--option-a.scss
  core/scss/components/lockup/_lockup--option-b.scss
  core/scss/components/lockup/_lockup--option-c.scss
  core/scss/components/lockup/_lockup--option-d.scss
  core/scss/components/lockup/_lockup--option-e.scss
  core/scss/components/lockup/_lockup--option-f.scss
  core/scss/components/lockup/_lockup--option-g.scss
  core/scss/components/lockup/_lockup--option-h.scss
  core/scss/components/lockup/_lockup--option-i.scss
  core/scss/components/lockup/_lockup--option-j.scss
  core/scss/components/lockup/_lockup--option-k.scss
  core/scss/components/lockup/_lockup--option-l.scss
  core/scss/components/lockup/_lockup--option-m.scss
  core/scss/components/lockup/_lockup--option-n.scss
  core/scss/components/lockup/_lockup--option-o.scss
  core/scss/components/lockup/_lockup--option-p.scss
  core/scss/components/lockup/_lockup--option-q.scss
  core/scss/components/lockup/_lockup--option-r.scss
  core/scss/components/lockup/_lockup--option-s.scss
  core/scss/components/lockup/_lockup--option-t.scss
  core/scss/components/lockup/_lockup--two-lines.scss
  core/scss/components/lockup/_lockup.scss
  core/scss/components/lockup/index.scss
  core/scss/core/index.scss
  core/templates/components/lockup/lockup.json
  core/templates/components/lockup/lockup.twig
  package-lock.json
  package.json
Labels: enhancement

#345 Reorganize files for CTA so it's consistent with other components
  core/css/decanter.css
  core/scss/components/cta/_cta--button-bottom-icon.scss
  core/scss/components/cta/_cta--button-center.scss
  core/scss/components/cta/_cta.scss
  core/scss/components/cta/index.scss
  core/scss/utilities/mixins/cta/_cta.scss
  core/scss/utilities/mixins/cta/index.scss
  core/scss/utilities/mixins/layout/_centering.scss
  core/scss/utilities/mixins/layout/index.scss
Labels: maintenance

#344 Main Nav Light on Dark Background Color Variant
  core/css/decanter.css
  core/img/caret-down-black.svg
  core/img/caret-down-white.svg
  core/img/close-black.svg
  core/img/close-white.svg
  core/img/hamburger-black.svg
  core/img/hamburger-white.svg
  core/scss/components/main-nav/_main-nav--dark.scss
  core/scss/components/main-nav/_main-nav.scss
  core/scss/components/main-nav/index.scss
  core/scss/core/colors/index.scss
  core/scss/utilities/variables/core/_colors.scss
  kss/builder/decanter/kss-assets/css/kss.css
  kss/builder/decanter/scss/_main-nav.scss
Labels: enhancement

#343 Cut down on media queries generated by @modular-spacing
  core/css/decanter.css
  core/scss/utilities/mixins/modular-scale/_modular-spacing.scss
Labels: enhancement

#347 Use %placeholder and @extend on button mixins to see if it makes code less repetitive
  core/css/decanter.css
  core/scss/components/cta/_cta.scss
  core/scss/utilities/index.scss
  core/scss/utilities/mixins/button/_button-big.scss
  core/scss/utilities/mixins/button/_button-primary.scss
  core/scss/utilities/mixins/button/_button-secondary.scss
  core/scss/utilities/mixins/cta/index.scss
  core/scss/utilities/mixins/index.scss
  core/scss/utilities/placeholders/components/_button.scss
  core/scss/utilities/placeholders/components/_cta.scss
  core/scss/utilities/placeholders/components/index.scss
  core/scss/utilities/placeholders/index.scss
  kss/builder/decanter/kss-assets/css/kss.css
Labels: enhancement

#348 Replace KSS nav with main-nav component
  core/css/decanter.css
  core/scss/components/lockup/_lockup.scss
  core/scss/components/main-nav/_main-nav--center.scss
  core/scss/components/main-nav/_main-nav--right.scss
  core/scss/components/main-nav/_main-nav.scss
  kss/builder/decanter/index.twig
  kss/builder/decanter/kss-assets/css/kss.css
  kss/builder/decanter/kss-assets/js/main-nav.js
  kss/builder/decanter/scss/_builder.scss
  kss/builder/decanter/scss/_content.scss
  kss/builder/decanter/scss/_home.scss
  kss/builder/decanter/scss/_main-nav.scss
  kss/builder/decanter/scss/_masthead.scss
Labels: enhancement
