Repository SU-SWS/decanter, pull requests merged in 2019-10, with the labels that each got.

#503 Add 4 new @modular-spacing steps (#6 to #9) and modify 2 existing steps (#3 and #4)
  core/dist/css/decanter.css
  core/src/scss/utilities/functions/modular-scale/_calculate-modular-spacing.scss
  core/src/scss/utilities/functions/modular-scale/_get-modular-spacing-multiplier.scss
  core/src/scss/utilities/mixins/modular-scale/_modular-spacing.scss
  core/src/scss/utilities/variables/core/_modular-spacing.scss
Labels: enhancement

#498 Scale down type-a and type-b font size at xs and sm breakpoints, repurpose splash font and minor typography tweaks
  core/dist/css/decanter.css
  core/src/scss/elements/typography/_typography.scss
  core/src/scss/utilities/mixins/typography/_font-splash.scss
  core/src/scss/utilities/mixins/typography/_intro-text.scss
  core/src/scss/utilities/mixins/typography/_type-a.scss
  core/src/scss/utilities/mixins/typography/_type-b.scss
  core/src/scss/utilities/mixins/typography/_type-c.scss
  core/src/scss/utilities/mixins/typography/_type-d.scss
  core/src/scss/utilities/mixins/typography/_types.scss
  core/src/scss/utilities/mixins/typography/index.scss
  core/src/scss/utilities/variables/core/_typography.scss
Labels: enhancement

#504 Add parameter to @link-icon to adjust vertical position of icon and different options for $animate parameter
  core/dist/css/decanter.css
  core/src/img/lock-solid.svg
  core/src/scss/components/link/_link--download.scss
  core/src/scss/components/link/_link--external.scss
  core/src/scss/components/link/_link--internal.scss
  core/src/scss/components/link/_link--jump.scss
  core/src/scss/components/link/_link--video.scss
  core/src/scss/utilities/mixins/link/_link-glyph.scss
  core/src/scss/utilities/mixins/link/_link-icon.scss
Labels: enhancement

#500 Adding global footer variants and link tweaks for legibility, change layout at MD breakpoint to match Figma
  Gruntfile.js
  core/dist/css/decanter.css
  core/src/scss/components/global-footer/_global-footer--bright.scss
  core/src/scss/components/global-footer/_global-footer--dark.scss
  core/src/scss/components/global-footer/_global-footer.scss
  core/src/scss/components/global-footer/index.scss
  core/src/templates/components/brand-bar/brand-bar.twig
  core/src/templates/components/global-footer/global-footer.twig
  core/src/templates/components/logo/logo.twig
Labels: Accessibility, enhancement

#513 Update _hero.scss
  core/src/scss/components/hero/_hero.scss
  core/src/templates/components/hero/hero.twig
Labels: bug
