Repository SU-SWS/decanter, pull requests merged in 2021-08, with the labels that each got.

#843 ADAPT-2539: Add stretched-link and writing-mode utilities to v7
  src/plugins/components/link/stretched-link.js
  src/plugins/utilities/typography/writing-mode.js
  tailwind.config.js
Labels: beta, size/xs

#846 Update _lockup.scss
  .github/workflows/autorelease.yml
  .npmrc
  core/dist/css/decanter.css
  core/src/scss/components/lockup/_lockup.scss
  package-lock.json
  package.json
Labels: size/s, patch

#848 Add autochangelog
  package-lock.json
  package.json
Labels: patch
