Repository SU-SWS/decanter, pull requests merged in 2021-05, with the labels that each got.

#825 ADAPT-2518: Added autorelease github action.
  .github/autorelease.yml
  .npmrc
  package-lock.json
  package.json
Labels: alpha, size/xl

#828 Set autorelease branch to v7
  .github/autorelease.yml
Labels: alpha

#829 ADAPT-000: Move workflow file
  .github/workflows/autorelease.yml
Labels: alpha, size/xs

#830 Add package npm script for autorelease.
  package.json
Labels: alpha

#832 Automatic Release Testing
  package.json
Labels: alpha

#827 Added Config viewer
  package-lock.json
  package.json
Labels: alpha, size/xl

#834 Added 4,6,8 pixel border widths
  src/plugins/theme/borderWidth.js
Labels: alpha, size/xs
