Repository SU-SWS/decanter, pull requests merged in 2022-04, with the labels that each got.

#867 Release-6.2.6
  CHANGELOG.md
  README.md
Labels: size/xs, patch

#868 DEC-000: Use NVM on GH Action.
  .github/workflows/autorelease.yml
Labels: size/xs

#874 Remove package action
  .github/workflows/autorelease.yml
Labels: size/xs

#875 Fixup! Typo.
  package.json
Labels: rc
