Repository SU-SWS/decanter, pull requests merged in 2023-02, with the labels that each got.

#892 feat: Add font-display swap support to font loading
  .github/auto-label.json
  .github/workflows/label.yml
  core/dist/css/decanter.css
  core/src/scss/core/fonts/_fonts.scss
Labels: patch

#893 Fixup! github release workflow.
  .github/workflows/autorelease.yml
  .nvmrc
  package-lock.json
Labels: patch

#894 Update autorelease.yml
  .github/workflows/autorelease.yml
Labels: patch

#895 Update autorelease.yml
  .github/workflows/autorelease.yml
Labels: patch

#896 Update autorelease.yml
  .github/workflows/autorelease.yml
Labels: patch

#897 Commit build changes.
  .github/workflows/autorelease.yml
Labels: patch

#898 All the fixes today.
  .github/workflows/autorelease.yml
Labels: patch

#899 All the fixes today.
  .github/workflows/autorelease.yml
Labels: patch

#904 SDSS-234: Removal of title on non interactive element for a11y
  core/src/templates/components/global-footer/global-footer.twig
Labels: size/xs, patch

#905 Update TailwindCSS and other plugins; add utilities; update nvmrc
  .nvmrc
  package-lock.json
  package.json
  src/plugins/theme/fontSize.js
  tailwind.config.js
Labels: size/m, rc
